-- Run this after add-new-meals-from-spreadsheet.sql to see exactly which of the 113
-- candidate meals now exist in your library and when each was created -- rows with a
-- created_at from today are the ones the import script just added; older created_at
-- (or you'd already added it yourself before running the script) means it was already
-- there and the script correctly left it untouched.

with candidates(name, category) as (
  values
  ('Overnight Oats', 'breakfast'),
  ('Breakfast Bagel', 'breakfast'),
  ('PB&J Bagel', 'breakfast'),
  ('Porridge', 'breakfast'),
  ('Eggs', 'breakfast'),
  ('Yogurt', 'breakfast'),
  ('Overnight Weetabix', 'breakfast'),
  ('Avacado on Toast', 'breakfast'),
  ('Breafkast Wrap', 'breakfast'),
  ('Protein Pancakes', 'breakfast'),
  ('Chia Pudding', 'breakfast'),
  ('Chicken Sausage Bagel', 'breakfast'),
  ('Honey Bagel', 'breakfast'),
  ('Avacado and Egg', 'breakfast'),
  ('Oats and Water', 'breakfast'),
  ('Sticky Toffee Baked Oats', 'breakfast'),
  ('Carrot Cake Baked Oats', 'breakfast'),
  ('Flavoured Hot Cross Bun', 'breakfast'),
  ('Apple Crumble Baked Oats', 'breakfast'),
  ('Jam Crumpets', 'breakfast'),
  ('Sausages, Beans and Toast', 'breakfast'),
  ('Biscoff Overnight Oats', 'breakfast'),
  ('Strawberry Cheesecake Overnight Oats', 'breakfast'),
  ('Jam Bagel', 'breakfast'),
  ('Sweet Chilli Chicken Wrap', 'lunch'),
  ('Chicken Sausage Bagel', 'lunch'),
  ('Avacado and Egg on Sourdough', 'lunch'),
  ('Chicken and Rice', 'lunch'),
  ('Tuna Pasta', 'lunch'),
  ('Chicken and Sweet Potato', 'lunch'),
  ('Beans on Toast', 'lunch'),
  ('Tuna Bun', 'lunch'),
  ('Tuna Pita', 'lunch'),
  ('Avacado Bagel', 'lunch'),
  ('Tuna Bagel', 'lunch'),
  ('Chicken and Egg Fried Rice', 'lunch'),
  ('BBQ Chicken Wrap', 'lunch'),
  ('Jerk Chicken Cheese Burger', 'lunch'),
  ('Club Sandwich', 'lunch'),
  ('Cheesy Chicken and Chorizo Wrap', 'lunch'),
  ('Cheese Burger Wrap', 'lunch'),
  ('Nandos Chicken Cibatta', 'lunch'),
  ('Scrambled Egg Bagel', 'lunch'),
  ('Roasted Tomato Pepper and Feta Soup', 'lunch'),
  ('Chicken and Veg Soup', 'lunch'),
  ('Chicken Salad', 'lunch'),
  ('Crispy Chilli Chicken Wrap', 'lunch'),
  ('BBQ Chicken Pita', 'lunch'),
  ('Pesto Chicken Cibatta', 'lunch'),
  ('Pesto Chicken Pannini', 'lunch'),
  ('Egg Salad Bun', 'lunch'),
  ('Ham and Cheese Toastie', 'lunch'),
  ('Chicken Pita', 'lunch'),
  ('Chicken, Rice and Veg', 'lunch'),
  ('Chicken Caesar Salad', 'lunch'),
  ('Roast Ham Sandwich', 'lunch'),
  ('Naked Borrito', 'lunch'),
  ('Rice Cakes', 'pre_workout'),
  ('Cereal', 'pre_workout'),
  ('Oats', 'pre_workout'),
  ('Bagel Thin', 'pre_workout'),
  ('Sweet Potato', 'pre_workout'),
  ('Crumpets', 'pre_workout'),
  ('Squares Bar and Banana', 'pre_workout'),
  ('Protein Yogurt (Pouch)', 'pre_workout'),
  ('Jam Crumpet Thins', 'pre_workout'),
  ('Jam Bagel', 'pre_workout'),
  ('Steak and Poatoes', 'dinner'),
  ('Chicken and Potatos', 'dinner'),
  ('Fajitas', 'dinner'),
  ('Smash Burger', 'dinner'),
  ('Salmon and Potatoes', 'dinner'),
  ('Stir Fry', 'dinner'),
  ('Chicken and Rice', 'dinner'),
  ('Chicken Burger', 'dinner'),
  ('Burger Bowl', 'dinner'),
  ('Tortilla Pizza', 'dinner'),
  ('Chicken and Sweet Potato', 'dinner'),
  ('Sticky Honey Chicken and Rice', 'dinner'),
  ('Cheesy Beef Pasta', 'dinner'),
  ('Creamy Chicken Pasta', 'dinner'),
  ('Chicken, Hallouimi and Chorizo Pasta', 'dinner'),
  ('Sweet Chilli Chicken Egg Fried Rice', 'dinner'),
  ('Creamy Garlic Cheesy Chicken & Potatos', 'dinner'),
  ('Cheesy BBQ Chicken Loaded Fries', 'dinner'),
  ('Creamy Cajun Chicken Pasta', 'dinner'),
  ('Chicken and Chorizo Rice', 'dinner'),
  ('Spaghetti Bolognase', 'dinner'),
  ('BBQ Chicken Pizza', 'dinner'),
  ('Big Mac Loaded Fries', 'dinner'),
  ('Chilli and Wedges', 'dinner'),
  ('Nandos Orzo', 'dinner'),
  ('Chicken Sausage and Mascarpone', 'dinner'),
  ('Chicken and Bacon Potato Pie', 'dinner'),
  ('Jacket Potato, Tuna, Cheese and Onion', 'dinner'),
  ('Chicken Fajitas', 'dinner'),
  ('Creamy Nandos Chicken Pasta', 'dinner'),
  ('Beef Tacos', 'dinner'),
  ('Mayflower Curry', 'dinner'),
  ('Chicken Pita and Sweet Potato Fries', 'dinner'),
  ('Chicken Chow Mein', 'dinner'),
  ('Potato Fajitas', 'dinner'),
  ('Jacket Potato, Beans and Cheese', 'dinner'),
  ('Chicken Sausage and Sweet Potato Mash', 'dinner'),
  ('Reduced Lasange', 'dinner'),
  ('Cheesey Chicken and Broccoli Pasta', 'dinner'),
  ('Greek Yogurt', 'evening_snack'),
  ('Bagel Thin', 'evening_snack'),
  ('Rice Cakes', 'evening_snack'),
  ('Cinnamon and Raisin Bagel', 'evening_snack'),
  ('Peanut Butter Bagel Thin', 'evening_snack'),
  ('Kinder Protein Cheesecake', 'snack'),
  ('Banana and Raspberry Biscoff Baked Oats', 'snack')
)
select
  c.name,
  c.category,
  m.id is not null as exists_in_library,
  m.created_at
from candidates c
left join meals m
  on m.coach_id = (select id from profiles where email = 'annabelatherton@gmail.com')
  and m.category = c.category
  and lower(trim(m.name)) = lower(trim(c.name))
order by exists_in_library, c.category, c.name;
