-- Replaces every variation's auto-generated coaching cue with a real,
-- exercise-specific one: setup, how to perform it, and a notable tip —
-- matched to the coach's actual (exercise, equipment) rows exported from
-- exercise_variations. Uses dollar-quoting ($$...$$) so apostrophes in the
-- text ("don't", "you're") don't need escaping. Safe to re-run — each
-- statement just overwrites that one row's coaching_cues again.
-- Run once in Supabase SQL Editor.

UPDATE exercise_variations SET coaching_cues = $$Kneel on a pad with the wheel under your shoulders and roll forward slowly, keeping your arms straight and hips tucked under. Stop before your lower back arches, then pull back to the start. Go only as far as you can control the return — depth isn't the goal, staying braced is.$$ WHERE id = '1e7a9e71-5914-490b-bbc7-edc47237a188';

UPDATE exercise_variations SET coaching_cues = $$Set the bar in a rack at roughly chest height, step under it and rest it across your upper traps with your feet shoulder-width apart. Break at the hips and knees together, sitting back until your thighs are at least parallel, then drive through the whole foot to stand. Keep your chest up and brace your core hard before you unrack.$$ WHERE id = 'ab986e23-c5e3-40cf-a214-26e2d278a742';

UPDATE exercise_variations SET coaching_cues = $$Lie on the bench with your eyes under the bar, feet flat on the floor, and grip just outside shoulder width. Unrack, lower the bar under control to touch your chest, then press back up in a straight line without flaring your elbows to 90°. Keep your shoulder blades pinned together throughout the set.$$ WHERE id = 'e817744e-bef3-4dc4-b92a-8e997c3eb403';

UPDATE exercise_variations SET coaching_cues = $$Hinge at the hips with a slight knee bend until your torso is close to parallel to the floor, gripping the bar just outside your legs. Row the bar into your lower ribs, driving your elbows back and squeezing your shoulder blades together, then lower under control. Keep your back flat — if you're rounding, the weight's too heavy.$$ WHERE id = '6d86e937-18ee-4688-a31d-3c2ce5df4396';

UPDATE exercise_variations SET coaching_cues = $$Stand tall holding the bar with an underhand, shoulder-width grip and your elbows pinned to your sides. Curl the bar up by bending only at the elbow, then lower it back down under control without swinging your torso. Keep your elbows locked in place the whole set — if they drift forward, drop the weight.$$ WHERE id = '3d42ca3f-3228-4911-9ebb-65bf9c590617';

UPDATE exercise_variations SET coaching_cues = $$Stand facing the low pulley with an underhand grip on the handle and your elbows tucked to your sides. Curl the handle up under control, squeeze at the top, then let the cable pull your arm back down slowly. The constant tension means there's no easy point in the rep — resist the urge to rush the bottom half.$$ WHERE id = 'd7d0fa12-1afb-41d8-8982-d1e60a9d63ca';

UPDATE exercise_variations SET coaching_cues = $$Stand with a dumbbell in each hand, palms facing forward, elbows pinned to your sides. Curl both (or alternate) up under control, squeeze at the top, then lower slowly all the way down. Keep your wrists straight and avoid swinging the weight up with your hips.$$ WHERE id = '8de05057-7c4d-44de-a717-5470a8dcb9f3';

UPDATE exercise_variations SET coaching_cues = $$Grip the angled part of the EZ bar with an underhand grip and your elbows tucked to your sides. Curl the bar up under control without letting your elbows drift forward, then lower it slowly back down. The angled grip is easier on the wrists — use it to focus purely on squeezing the biceps.$$ WHERE id = '2784f767-4ef1-4412-a255-a1c01b9b2061';

UPDATE exercise_variations SET coaching_cues = $$Sit down and adjust the seat so your elbows line up with the machine's pivot point, then take a full grip on the handles. Curl through a full range of motion, squeeze at the top, then control the weight back down. Let the machine guide the path so you can focus entirely on the squeeze.$$ WHERE id = '41fd75ea-6e6c-44fc-ad31-b34a87fd63e3';

UPDATE exercise_variations SET coaching_cues = $$Set a box or bench at a height just below parallel behind you, and unrack the bar across your upper traps as you would for a normal squat. Sit back onto the box under control, pause briefly without relaxing your brace, then drive back up through your heels. Keep tension throughout the pause — this isn't a rest, it's a dead-stop start for the next rep.$$ WHERE id = 'd4d5313f-7a65-48e9-82c8-068157d7460d';

UPDATE exercise_variations SET coaching_cues = $$Rest the top of your rear foot on a bench behind you, holding a dumbbell in each hand, with your front foot far enough forward that your knee stays over your ankle. Lower straight down until your rear knee nearly touches the floor, then drive up through your front heel. Push your hips forward at the top and squeeze the glute of your working leg.$$ WHERE id = 'c99cef3b-d9c1-4dc4-84c9-30ab6c868bb4';

UPDATE exercise_variations SET coaching_cues = $$Set the bar on your upper back in the Smith machine, rear foot up on a bench behind you and your front foot out far enough that your knee tracks over your ankle. Lower under control until your rear knee nearly touches the floor, then drive up through your front heel. The fixed bar path lets you lean slightly forward to load the glute harder.$$ WHERE id = '0eeb8ccb-f5e6-4827-ba3c-631aed385539';

UPDATE exercise_variations SET coaching_cues = $$Rest the top of your rear foot on a bench behind you holding a dumbbell in each hand, with your front foot positioned closer under your hips than the glute-focused version. Lower straight down keeping your torso upright, then drive up through your front foot. Staying more upright shifts the emphasis onto the quad rather than the hip.$$ WHERE id = 'cb1d5c8e-9f82-47c1-9365-b76c04a4a6b5';

UPDATE exercise_variations SET coaching_cues = $$Set the bar on your upper back in the Smith machine, rear foot up on a bench, front foot positioned under your hips with your torso upright. Lower under control until your rear knee nearly touches the floor, then drive up through your front foot. Keep your torso vertical throughout — leaning forward shifts the work onto the glute instead.$$ WHERE id = '7e5f3b55-155e-4df7-b511-471ce339cdf7';

UPDATE exercise_variations SET coaching_cues = $$Kneel below a high pulley holding the rope behind your head, hips stacked over your knees. Curl your torso down by rounding your spine and bringing your elbows toward your thighs, then return under control without letting the weight stack rest. Move from your abs, not your hips — your hips should barely shift.$$ WHERE id = 'dbd1c36f-9dd5-4670-9e09-01ce9110a2b2';

UPDATE exercise_variations SET coaching_cues = $$Stand facing the low pulley with an underhand grip on the handle and your elbows tucked to your sides. Curl the handle up under control, squeeze hard at the top, then let the cable pull your arm back down slowly. Keep constant tension on the bicep — don't let the weight stack touch down between reps.$$ WHERE id = '9662d852-fcf6-4da9-b8b9-816bf189c381';

UPDATE exercise_variations SET coaching_cues = $$Attach an ankle cuff to a low pulley and hinge slightly forward, holding the frame for balance. Kick your leg straight back and up, squeezing your glute hard at the top, then return under control without letting momentum swing the leg back. Keep your standing leg soft and avoid arching your lower back to gain extra range.$$ WHERE id = '46c87e9d-1d5f-4b69-aef6-1701a1c18bdd';

UPDATE exercise_variations SET coaching_cues = $$Face away from a low pulley with the rope between your legs, feet shoulder-width apart. Hinge at the hips, pushing them back until you feel a stretch in your hamstrings and glutes, then drive your hips forward to standing, squeezing your glutes hard at the top. Keep the movement in your hips — this isn't a squat, so keep your knees only softly bent.$$ WHERE id = '2da210b8-90b2-44f2-9bd8-5ae591a63e2d';

UPDATE exercise_variations SET coaching_cues = $$Set both pulleys to chest height and stand in the middle with a slight forward lean and soft elbow bend. Bring your hands together in front of your chest in a wide arc, squeeze, then let your arms open back out under control. Keep the same slight elbow bend throughout — don't let it turn into a press.$$ WHERE id = '874f0c08-2745-4f98-9a0b-9087c2635008';

UPDATE exercise_variations SET coaching_cues = $$Lie on a flat bench holding a dumbbell in each hand above your chest, palms facing in, with a slight bend in your elbows. Lower the weights out to the sides in a wide arc until you feel a stretch across your chest, then bring them back together over your chest. Keep that same elbow bend locked in the whole set — bending more turns it into a press.$$ WHERE id = '3eed6b10-e300-471c-b31c-e63b4fc7e0c2';

UPDATE exercise_variations SET coaching_cues = $$Sit tall with your back against the pad and grip the handles with your elbows at chest height. Bring your arms together in front of you, squeeze your chest hard, then let the weight stretch you back out under control. Focus on squeezing your chest together rather than just moving the handles.$$ WHERE id = '13d30e98-3b7f-4d21-99f8-a99bcf94c9d9';

UPDATE exercise_variations SET coaching_cues = $$Lie face-down on an incline bench with a barbell underneath you, gripping just outside shoulder width. Row the bar up into your lower chest, driving your elbows back and squeezing your shoulder blades together, then lower under control. The bench removes any momentum from your legs or back — if you're straining to move the weight, it's too heavy.$$ WHERE id = '6002684a-580a-4a2d-83bd-59225048a331';

UPDATE exercise_variations SET coaching_cues = $$Lie face-down on an incline bench holding a dumbbell in each hand, arms hanging straight down. Row both dumbbells up toward your hips, squeezing your shoulder blades together at the top, then lower under control. Keep your chest pinned to the bench throughout — don't let it lift off to cheat the weight up.$$ WHERE id = '4a8ca845-ebdd-43d1-bd57-eada1c6cb663';

UPDATE exercise_variations SET coaching_cues = $$Adjust the chest pad so it sits firmly against your chest and grip the handles with your arms extended. Row the handles back, driving your elbows behind you and squeezing your shoulder blades together, then extend back out under control. Keep your chest pressed into the pad the entire set.$$ WHERE id = '9ea3cfb9-f831-4f00-9acf-30b7755cd0df';

UPDATE exercise_variations SET coaching_cues = $$Lie on the bench and grip the bar just inside shoulder width, closer than a normal bench press. Lower the bar to your lower chest keeping your elbows tucked close to your body, then press back up focusing on straightening your arms. Keeping the elbows tucked (not flared) is what shifts the work onto the triceps.$$ WHERE id = 'bac68fe8-a650-4c68-87f3-913076ec0d93';

UPDATE exercise_variations SET coaching_cues = $$Sit on a bench with your legs spread, brace the back of your working arm against the inside of your thigh, and let the dumbbell hang straight down. Curl it up under control, squeeze hard at the top, then lower it fully back down. Bracing your elbow against your leg stops any momentum, so the bicep does all the work.$$ WHERE id = '3c3c71cc-49f3-4de5-843c-61a6eaf825e1';

UPDATE exercise_variations SET coaching_cues = $$Lie on your back with your knees bent and feet flat, hands lightly touching your ears. Curl your shoulder blades up off the floor by contracting your abs, then lower back down under control. Keep the movement small and controlled — don't pull on your neck to generate the crunch.$$ WHERE id = '6b25866b-39bf-40fb-9e61-d3c86be905d3';

UPDATE exercise_variations SET coaching_cues = $$Kneel below a high pulley holding the rope behind your head, hips stacked over your knees. Curl your torso down by rounding your spine and bringing your elbows toward your thighs, then return under control without letting the weight stack rest between reps. Move from your abs, not your hips.$$ WHERE id = '6f5c8a2b-9f11-4b89-8841-766d0872f41b';

UPDATE exercise_variations SET coaching_cues = $$Sit in the machine with the pads positioned across your chest or shoulders as set up by the machine, and grip the handles. Curl your torso forward by contracting your abs, squeeze at the bottom of the movement, then return under control. Resist the urge to yank the handles — let your abs do the work, not your arms.$$ WHERE id = '3f7980e4-0af3-4608-aa28-a1d6a50d0a4a';

UPDATE exercise_variations SET coaching_cues = $$Lie on your back with your knees bent and feet flat, hands lightly touching your ears. Curl your shoulder blades up off the floor by contracting your abs, then lower back down under control. Keep the movement small and controlled — don't pull on your neck to generate the crunch.$$ WHERE id = 'b036aca8-5568-4f8f-885f-8c5c67156c84';

UPDATE exercise_variations SET coaching_cues = $$Lie on your back with your arms reaching straight up and knees bent to 90° above your hips. Slowly lower one arm overhead and the opposite leg out straight while keeping your lower back pressed into the floor, then return and switch sides. The moment your back arches off the floor, you've gone too far — that's the range that counts.$$ WHERE id = '3d5b74f7-1222-4741-987c-56839251b626';

UPDATE exercise_variations SET coaching_cues = $$Stand with the bar over your mid-foot, grip just outside your legs, and set your hips down until your shins touch the bar with your back flat. Drive through the floor, keeping the bar close to your legs the whole way up, and finish by standing tall with your hips through. Keep your back flat throughout — if it rounds, reset and brace again before pulling.$$ WHERE id = '3369e76b-6b93-4c7b-a407-65d6a86d6cf7';

UPDATE exercise_variations SET coaching_cues = $$Hold a dumbbell vertically against your chest with both hands and stand with your feet slightly wider than shoulder width, toes turned out. Squat down as deep as your mobility allows, letting your knees track out over your toes, then drive back up. Sitting deep and wide is what shifts the emphasis onto the glutes.$$ WHERE id = '0b5c5a52-990d-4318-8adf-d2c9899e42db';

UPDATE exercise_variations SET coaching_cues = $$Load the machine and hold the handles at chest height, feet set wide with toes turned out. Squat down as deep as comfortable, letting your knees track over your toes, then drive back up through your heels. Keep your chest tall throughout — the wide, deep stance is what makes this a glute-focused squat.$$ WHERE id = 'cae2ada0-1c0f-40d4-a4bc-ced0b5d8b88d';

UPDATE exercise_variations SET coaching_cues = $$Support yourself on parallel bars with your arms straight, then lean your torso forward slightly. Lower yourself under control until your shoulders dip below your elbows, then press back up to full lockout. Leaning forward and letting your elbows flare naturally shifts more of the work onto your chest.$$ WHERE id = '9e960f60-facc-4c0a-ad98-87627ac29578';

UPDATE exercise_variations SET coaching_cues = $$Set the machine to a suitable assistance or resistance level, then grip the handles and lean your torso forward slightly. Lower under control until your shoulders dip below your elbows, then press back up. Keep the forward lean throughout to keep the emphasis on your chest rather than your triceps.$$ WHERE id = '5cec6dc8-5896-43c9-8ad4-a7c39069efde';

UPDATE exercise_variations SET coaching_cues = $$Set the rope at face height and pull the handles toward your forehead while keeping your elbows high and flared out. Squeeze your back and control the eccentric. Finish each rep with your hands wide and thumbs pointing back, like you're pulling the rope apart.$$ WHERE id = '7eeaf6c2-5ad9-4011-8670-a9620cc5b804';

UPDATE exercise_variations SET coaching_cues = $$Rack the bar across the front of your shoulders with your elbows lifted high, either crossing your arms over the bar or using a clean grip. Squat down keeping your torso upright and elbows up, then drive back through your heels to stand. The moment your elbows drop, the bar wants to roll forward — keep them high the whole set.$$ WHERE id = 'a66cfc1b-1bce-48f5-a70c-e412f414d22b';

UPDATE exercise_variations SET coaching_cues = $$Hold a dumbbell vertically against your chest with both hands, feet about shoulder-width apart. Squat down keeping your torso upright and elbows brushing the inside of your knees at the bottom, then drive back up. Keep the weight close to your chest throughout to stay balanced.$$ WHERE id = '8957d422-0cc9-48de-afe1-525fbb94e794';

UPDATE exercise_variations SET coaching_cues = $$Set the bar across your upper back as you would for a squat, feet shoulder-width apart and a soft bend in your knees. Hinge forward at the hips, pushing them back until your torso is close to parallel with the floor, then drive your hips forward to stand tall. Keep your back flat and the bar's path close to your body throughout.$$ WHERE id = '3d8868c8-b182-4232-b8a2-15e268e70bd9';

UPDATE exercise_variations SET coaching_cues = $$Set the bar across your upper back in the Smith machine, feet shoulder-width apart with a soft knee bend. Hinge at the hips, pushing them back until your torso nears parallel with the floor, then drive your hips forward to stand tall. The fixed bar path lets you focus purely on the hip hinge without worrying about balance.$$ WHERE id = '7ec1976f-ce73-4805-9d34-515eadddd771';

UPDATE exercise_variations SET coaching_cues = $$Set your shoulders and back firmly against the pads with your feet shoulder-width apart on the platform, positioned slightly in front of your hips. Lower under control until your thighs are at least parallel, then drive back up through your whole foot. Keep your lower back pressed into the pad the whole set — don't let it round at the bottom.$$ WHERE id = '6d861392-1a68-4132-a511-5ab3c27afd36';

UPDATE exercise_variations SET coaching_cues = $$Stand holding a dumbbell in each hand with a neutral, palms-facing-in grip, elbows pinned to your sides. Curl both (or alternate) up under control without rotating your wrists, then lower slowly. The neutral grip shifts more emphasis onto the forearm and the outer head of the bicep.$$ WHERE id = 'f7809742-b454-4426-9179-4ee993897228';

UPDATE exercise_variations SET coaching_cues = $$Hang from the bar with a full grip and your legs straight (or knees bent for an easier version). Raise your legs up in front of you by curling your pelvis under, then lower back down under control without swinging. Control the descent — swinging the weight up using momentum takes the tension off your abs.$$ WHERE id = '6ca5c22a-0694-4d7f-84c0-a5137c26de0f';

UPDATE exercise_variations SET coaching_cues = $$Set both pulleys above shoulder height and stand in the middle with a slight forward lean. Pull your hands down and together in front of your hips in a wide arc, squeezing your lower chest, then let them return under control. Keep a slight bend in your elbows throughout — locking them out turns it into a pull instead of a fly.$$ WHERE id = '0d1b6467-c443-4d62-8ba5-20554d98224b';

UPDATE exercise_variations SET coaching_cues = $$Sit in the machine with the pads against the outside of your knees/thighs and your back flat against the seat. Push your legs apart against the resistance, squeezing your outer glutes at the widest point, then return under control. Avoid rocking your torso to help move the weight — let your legs do all the work.$$ WHERE id = 'b07a8d38-6775-41f7-a8e6-1d5a74167fd6';

UPDATE exercise_variations SET coaching_cues = $$Sit in the machine with the pads against the inside of your knees/thighs and your back flat against the seat. Squeeze your legs together against the resistance, pause briefly at the middle, then return under control. Move through a full range rather than using short, fast reps.$$ WHERE id = '4a3f096a-b99e-49f8-aedb-7ec57450492f';

UPDATE exercise_variations SET coaching_cues = $$Sit in the machine with the pads against the inside of your knees/thighs and your back flat against the seat. Squeeze your legs together against the resistance, pause briefly at the middle, then return under control. Move through a full range rather than using short, fast reps.$$ WHERE id = 'bd17fd90-d387-4b9c-a7b6-a5e122d76272';

UPDATE exercise_variations SET coaching_cues = $$Set your upper back against a bench with the bar sitting across your hip crease (pad it if needed), feet flat and shins vertical. Drive your hips up until your body forms a straight line from shoulders to knees, squeezing your glutes hard at the top, then lower under control. Keep your chin tucked and don't let your lower back arch to gain extra height.$$ WHERE id = '9dd2a92b-0373-4c43-bc33-dfd86cadfd73';

UPDATE exercise_variations SET coaching_cues = $$Sit into the machine with the pad across your hip crease and your feet set on the platform, shins vertical. Drive your hips up into the pad, squeezing your glutes hard at the top, then return under control. Push through your heels rather than your toes to keep the tension on your glutes.$$ WHERE id = '3bbf5a9e-4700-493e-99d2-28f6f3d866af';

UPDATE exercise_variations SET coaching_cues = $$Set your upper back against a bench with your hips under the bar or machine pad, feet flat and shins vertical. Drive your hips up until your body forms a straight line from shoulders to knees, squeezing your glutes hard at the top, then lower under control. Keep your chin tucked and avoid arching your lower back to gain extra height.$$ WHERE id = '5ed3985f-fc9f-4e86-847b-5a4f31779c36';

UPDATE exercise_variations SET coaching_cues = $$Set up the same as a barbell hip thrust, driving your hips up until your body forms a straight line from shoulders to knees. Instead of coming straight back down, hold at the top for the full count, squeezing your glutes as hard as you can. Keep breathing through the hold — don't just brace and hope the time passes.$$ WHERE id = '162fcffe-bf86-489c-a0c1-cb3fd8f88878';

UPDATE exercise_variations SET coaching_cues = $$Set up the same as the machine hip thrust, driving your hips up into the pad until fully extended. Hold at the top for the full count, keeping your glutes squeezed hard throughout rather than relaxing into the pad. Keep your ribs down and avoid arching your lower back to hold the position.$$ WHERE id = '3f51b50f-c35e-45a3-ac57-97c5e2e709d5';

UPDATE exercise_variations SET coaching_cues = $$Set your hips on the pad with your feet secured and your body forming a straight line, arms crossed over your chest (or holding a weight). Lower your torso down under control until you feel a stretch in your hamstrings/glutes, then raise back up until your body is straight — no further. Squeeze your glutes at the top rather than hyperextending your lower back.$$ WHERE id = '067a1c5c-8570-47f1-a716-9e4de463c27d';

UPDATE exercise_variations SET coaching_cues = $$Set the bench to a moderate incline and grip the bar just outside shoulder width, unracking over your upper chest. Lower the bar under control to your upper chest, then press back up in a straight line. Keep the incline moderate — too steep turns this into a shoulder press.$$ WHERE id = '01a9ab9b-3da3-45f0-9488-d974ea106107';

UPDATE exercise_variations SET coaching_cues = $$Set the bench to a moderate incline and press a dumbbell in each hand up from shoulder height. Lower under control until you feel a stretch across your upper chest, then press back up without clanking the weights together at the top. The dumbbells let each side work independently, so keep both arms moving at the same pace.$$ WHERE id = 'b45f59ff-5d60-443d-a020-2978c1c30e94';

UPDATE exercise_variations SET coaching_cues = $$Sit back against the pad and grip the handles at upper-chest height. Press forward and slightly up until your arms are extended, then lower back under control. Keep your shoulder blades pinned back against the pad throughout.$$ WHERE id = 'fb799008-df7e-4322-b006-031f2a58ec10';

UPDATE exercise_variations SET coaching_cues = $$Set an incline bench under the Smith machine bar and unrack it over your upper chest. Lower under control to your upper chest, then press back up in a straight line. The fixed bar path means you can focus purely on driving through your upper chest without balancing the bar.$$ WHERE id = 'ae6bb6e8-267a-473b-b8c8-801996e3aa79';

UPDATE exercise_variations SET coaching_cues = $$Lie face-down on an incline bench holding a dumbbell in each hand, arms hanging straight down. Raise your arms out to the sides with a slight elbow bend until they're roughly in line with your torso, then lower under control. Keep the movement slow — this is a small muscle, so momentum takes over easily if you rush it.$$ WHERE id = 'defb89a0-efcc-4df7-9560-9771877acdba';

UPDATE exercise_variations SET coaching_cues = $$Stand with the kettlebell on the floor in front of you, feet shoulder-width apart. Hinge at the hips to grip it, then drive your hips forward explosively to swing it up to chest height, keeping your arms relaxed. Let your hips do all the work — your arms are just along for the ride.$$ WHERE id = 'd4b6c52e-fe04-4e1e-a9ad-f73b83712701';

UPDATE exercise_variations SET coaching_cues = $$Sit under the bar with your knees secured under the pad and take a wide overhand grip. Pull the bar down to your upper chest, driving your elbows down and back, then let it rise back up under control without leaning back excessively. Lead with your elbows, not your hands, to keep the lats doing the work.$$ WHERE id = 'd4d74d32-ea64-43a1-b17c-61baa9c79a55';

UPDATE exercise_variations SET coaching_cues = $$Adjust the seat so the pivot lines up with your shoulders, then grip the handles or bar with your arms extended overhead. Pull down in an arc until your hands reach your thighs, keeping your arms mostly straight throughout, then let them rise back up under control. Keep a soft bend in your elbows — don't turn it into a tricep pushdown.$$ WHERE id = 'a063cf04-3dd6-48ef-80ba-067798509505';

UPDATE exercise_variations SET coaching_cues = $$Stand side-on to a low pulley and grip the handle with the arm furthest from the machine. Raise your arm out to the side up to shoulder height, leading with your elbow, then lower under control. The constant cable tension means the bottom of the rep stays loaded — don't let the weight stack rest between reps.$$ WHERE id = '67bad466-184a-4870-9787-5730324d8c76';

UPDATE exercise_variations SET coaching_cues = $$Stand holding a dumbbell in each hand by your sides, with a very slight bend in your elbows. Raise both arms out to the sides up to shoulder height, leading with your elbows, then lower under control. Keep the weight light enough that you're not swinging your torso to help lift it.$$ WHERE id = '831652e2-0418-479f-9351-6195490b1a0d';

UPDATE exercise_variations SET coaching_cues = $$Sit with your back against the pad and position your elbows against the machine's arm pads. Raise your arms out to the sides through the machine's set path, squeezing at the top, then lower under control. Let the machine guide the path so you can focus purely on the squeeze.$$ WHERE id = '7d837884-d58f-43bb-9fa1-8bb23240406e';

UPDATE exercise_variations SET coaching_cues = $$Stand holding a straight bar with a shoulder-width overhand grip in front of your thighs. Raise the bar up in front of you leading with your elbows, then lower under control. Keep your wrists neutral throughout — don't let them bend under the bar's weight.$$ WHERE id = '0cce0222-fbbb-4f04-ba25-5fbf47619ace';

UPDATE exercise_variations SET coaching_cues = $$Sit in the machine with the pad resting just above your ankles and your back flat against the seat. Extend your legs until they're straight, squeezing your quads hard at the top, then lower under control. Avoid using momentum to kick the weight up — control both directions evenly.$$ WHERE id = 'e3cd04e0-0e78-4a75-a7fd-7dd8499201d3';

UPDATE exercise_variations SET coaching_cues = $$Set your feet high and wide on the platform, toes turned slightly out, with your back and hips flat against the seat. Lower the platform until your knees are near your chest, then drive through your heels to extend, without locking your knees out hard. The higher, wider foot position shifts the emphasis onto your glutes.$$ WHERE id = '3e01fc1b-630f-48fd-a247-75e87d7014ea';

UPDATE exercise_variations SET coaching_cues = $$Set your feet lower and closer together on the platform, with your back and hips flat against the seat. Lower the platform under control until your knees approach your chest, then drive back up through your whole foot. The lower, narrower foot position keeps the emphasis on your quads.$$ WHERE id = '5a4713fe-e9b3-44d6-a7f6-5a8ed4fed8d9';

UPDATE exercise_variations SET coaching_cues = $$Sit with your chest against the pad (or braced upright) and grip the low handles with your arms extended. Row the handles back into your torso, driving your elbows back and squeezing your shoulder blades together, then extend back out under control. Keep your torso still throughout — the pull should come from your back, not your body rocking.$$ WHERE id = 'b9702589-ff0d-47bd-8224-71bc352af75c';

UPDATE exercise_variations SET coaching_cues = $$Set both pulleys low and stand in the middle with a slight forward lean. Pull your hands up and together in front of your upper chest in a wide arc, squeezing your chest at the top, then let them return under control. Keep a slight bend in your elbows the whole set to keep the tension on your chest.$$ WHERE id = 'a21abd34-4ee0-4013-9e07-bc6d456161fe';

UPDATE exercise_variations SET coaching_cues = $$Lie face-down on the machine with the pad resting just above your heels and your hips pressed into the bench. Curl your heels up toward your glutes, squeezing your hamstrings hard at the top, then lower under control. Keep your hips pinned to the bench — lifting them up is a sign the weight's too heavy.$$ WHERE id = '8e322a98-bb7a-4b7a-8c71-905b1bfac9ba';

UPDATE exercise_variations SET coaching_cues = $$Stand with the bar racked at your collarbone, grip just outside shoulder width. Press the bar straight overhead, moving your head back slightly to let it pass, then lower back to your collarbone under control. Keep your core braced hard throughout — this is a standing press, so there's no bench to steady you.$$ WHERE id = '4da97d22-deaa-46f2-afd2-752c990f89ab';

UPDATE exercise_variations SET coaching_cues = $$Set your shoulders against the pad with your feet centred on the platform, roughly shoulder-width apart. Lower under control along the machine's arcing path until your thighs are at least parallel, then drive back up through your whole foot. The arc does some of the balancing for you — focus on depth and control rather than fighting the path.$$ WHERE id = '1534a54d-a096-493c-b220-ae2c93c25dc0';

UPDATE exercise_variations SET coaching_cues = $$Prop yourself up on your forearms and toes with your body forming a straight line from head to heels. Brace your core and squeeze your glutes to hold the position without letting your hips sag or pike up. Breathe steadily throughout — holding your breath won't help you hold the position any longer.$$ WHERE id = 'f430b6e9-b28a-471c-a89c-1af3fce91abc';

UPDATE exercise_variations SET coaching_cues = $$Hold a weight plate (or dumbbell) with both hands in front of your thighs, arms straight. Raise it up in front of you to around shoulder height, leading with your hands, then lower under control. Keep a slight bend in your elbows and avoid leaning back to gain momentum.$$ WHERE id = '1a7212dd-b2cf-4781-ab9b-aaf909950553';

UPDATE exercise_variations SET coaching_cues = $$Set your upper arms against the preacher pad and grip the EZ bar with an underhand grip on the angled part. Curl the bar up under control, squeeze at the top, then lower it slowly until your arms are almost straight. The pad locks out any swinging, so keep the movement slow and deliberate.$$ WHERE id = '2176dc93-0038-4d14-b097-82f4029bc097';

UPDATE exercise_variations SET coaching_cues = $$Sit down with your upper arms against the preacher pad and grip the handles. Curl through a full range of motion, squeezing hard at the top, then lower under control until your arms are almost fully extended. Keep your shoulders relaxed down away from your ears throughout.$$ WHERE id = '57e9a674-dcbe-48d3-86ae-1d2a7ca34084';

UPDATE exercise_variations SET coaching_cues = $$Hang from the bar with a wide overhand grip, arms fully extended. Pull yourself up by driving your elbows down and back until your chin clears the bar, then lower back down under control to a full hang. Lead with your chest, not your chin, to keep the tension on your back.$$ WHERE id = 'a2b570c4-d426-4910-939c-79f55f9d9aab';

UPDATE exercise_variations SET coaching_cues = $$Set your hands slightly wider than shoulder width on the floor, body in a straight line from head to heels. Lower your chest to just above the floor keeping your elbows at roughly 45° from your body, then press back up to full extension. Keep your core and glutes braced throughout so your hips don't sag.$$ WHERE id = 'b29f0ac3-76b3-4ba0-8131-1bb6e6e18ede';

UPDATE exercise_variations SET coaching_cues = $$Stand holding the bar at hip height with a shoulder-width grip. Push your hips back, keeping a soft bend in your knees and the bar close to your legs, until you feel a deep stretch in your hamstrings, then drive your hips forward to stand tall. Keep your back flat throughout — this is a hip hinge, not a squat.$$ WHERE id = 'd3c33274-23d9-4aac-a998-6d4228e01285';

UPDATE exercise_variations SET coaching_cues = $$Stand holding a dumbbell in each hand in front of your thighs. Push your hips back, keeping a soft bend in your knees, and lower the weights close to your legs until you feel a stretch in your hamstrings, then drive your hips forward to stand tall. Keep the dumbbells close to your legs the whole way down and up.$$ WHERE id = '88880dd7-8133-4a79-a79e-c63c7dcd6cfb';

UPDATE exercise_variations SET coaching_cues = $$Set up in the machine with the pad positioned against your hips/thighs as designed for a hip hinge pattern. Push your hips back against the resistance until you feel a stretch through your hamstrings, then drive your hips forward to extend, squeezing your glutes at the top. Keep your back flat throughout the hinge.$$ WHERE id = 'add0dc60-5213-4eef-84bf-312369264f33';

UPDATE exercise_variations SET coaching_cues = $$Stand holding the weight at hip height. Push your hips back, keeping a soft bend in your knees, until you feel a deep stretch in your hamstrings, then drive your hips forward to stand tall, squeezing your glutes at the top. Keep your back flat throughout — this is a hip hinge, not a squat.$$ WHERE id = 'a5ed83d6-6d23-47af-82be-d9b1e4f724a2';

UPDATE exercise_variations SET coaching_cues = $$Set both pulleys at chest height and cross the cables (or use a single handle each), gripping the opposite handle with each hand. Pull your arms out and back in a wide arc, squeezing your shoulder blades together, then return under control. Keep a soft bend in your elbows throughout the set.$$ WHERE id = 'f5803956-8b2f-4b51-9a86-1fafc59852c2';

UPDATE exercise_variations SET coaching_cues = $$Hinge forward at the hips holding a dumbbell in each hand, arms hanging straight down. Raise your arms out to the sides with a slight elbow bend, squeezing your shoulder blades together at the top, then lower under control. Keep your torso still — the movement should come entirely from your shoulders.$$ WHERE id = '7e8021b1-958b-4ac0-8599-2c8956aa7c7a';

UPDATE exercise_variations SET coaching_cues = $$Sit facing into the machine, chest against the pad, and grip the handles in front of you with a slight elbow bend. Pull your arms out and back in a wide arc, squeezing your shoulder blades together, then return under control. Keep your chest pressed into the pad throughout to stop your torso from rocking.$$ WHERE id = '9cc29978-0882-4e8c-865b-dc45cda38c98';

UPDATE exercise_variations SET coaching_cues = $$Set the rope at face height and pull the handles toward your forehead, keeping your elbows high and flared out. Squeeze your rear delts and upper back at the peak, then control the return. Finish with your hands wide and thumbs pointing back.$$ WHERE id = 'bbee4326-b5c0-408c-88f8-cf2bc67d63f1';

UPDATE exercise_variations SET coaching_cues = $$Stand holding a dumbbell in each hand and step one foot backward into a lunge, lowering until your rear knee nearly touches the floor. Drive back up through your front heel to return to standing, then repeat on the other side. Push your hips forward as you drive up to keep the emphasis on your glutes.$$ WHERE id = '62f1e037-65b5-4c05-990a-185f9677cb29';

UPDATE exercise_variations SET coaching_cues = $$Set the bar across your upper back in the Smith machine and step one foot back into a lunge, lowering under control until your rear knee nearly touches the floor. Drive back up through your front heel to return to standing. The fixed bar path lets you focus on pushing your hips forward through each rep.$$ WHERE id = 'e102fd22-7690-4eb6-8cf2-8179e843f35b';

UPDATE exercise_variations SET coaching_cues = $$Sit with your knees bent and feet either flat or lifted off the floor, leaning back slightly with a straight spine. Rotate your torso to touch the floor on one side, then rotate through to the other side under control. Move slowly and with control — speed here usually means you're using momentum instead of your obliques.$$ WHERE id = '624a6fec-9cc2-4efc-b303-ff740950f8c3';

UPDATE exercise_variations SET coaching_cues = $$Sit in the machine with the pad resting across your lower thighs and the balls of your feet on the platform. Lower your heels down as far as your ankle mobility allows, then press up onto your toes, pausing briefly at the top. Move through a full range of motion — partial reps shortchange the stretch at the bottom.$$ WHERE id = '2814b309-e308-4fb3-bc90-b928d83e2daf';

UPDATE exercise_variations SET coaching_cues = $$Sit in the machine with the pad resting against the back of your lower legs and your back flat against the seat. Curl your legs down and back, squeezing your hamstrings hard at the bottom of the movement, then return under control. Keep your hips pressed into the seat throughout.$$ WHERE id = '3ed83a6e-3dbf-4956-8b99-34c488779851';

UPDATE exercise_variations SET coaching_cues = $$Sit on the end of a bench holding a dumbbell in each hand by your sides. Raise both arms out to the sides up to shoulder height, leading with your elbows, then lower under control. Sitting removes any leg drive, so keep the weight light enough to move with strict form.$$ WHERE id = '7c106691-1dee-463b-bc7d-420b667df4b6';

UPDATE exercise_variations SET coaching_cues = $$Sit at the cable row station with your knees slightly bent and grip the handle with your arms extended. Row the handle into your stomach, driving your elbows back and squeezing your shoulder blades together, then extend back out under control. Keep your torso upright throughout — don't rock back and forth to move the weight.$$ WHERE id = 'a0987e70-eab3-44ac-98f7-e83ad6553918';

UPDATE exercise_variations SET coaching_cues = $$Sit with your chest against the pad (or braced upright) and grip the handles with your arms extended. Row the handles back into your torso, squeezing your shoulder blades together, then extend back out under control. Keep your shoulders down away from your ears throughout the set.$$ WHERE id = '5988214f-e320-4b8d-9dec-3d872883fbca';

UPDATE exercise_variations SET coaching_cues = $$Sit or stand holding a dumbbell in each hand at shoulder height, palms facing forward. Press both dumbbells straight overhead until your arms are extended, then lower back down under control to shoulder height. Keep your core braced so your lower back doesn't arch as you press up.$$ WHERE id = 'd1ac8cba-7c1a-4ac0-aefb-c17e8d749d7b';

UPDATE exercise_variations SET coaching_cues = $$Sit with your back against the pad and grip the handles at shoulder height. Press up until your arms are extended (without locking out hard), then lower back down under control. Keep your shoulders down and back against the pad throughout the set.$$ WHERE id = '43c7f503-a766-42fc-9915-24f39609021a';

UPDATE exercise_variations SET coaching_cues = $$Sit on a bench positioned under the Smith machine bar, unracking it at shoulder height. Press the bar straight overhead, then lower back down under control to shoulder height. The fixed bar path means you can focus purely on driving up rather than balancing the weight.$$ WHERE id = 'f84653f4-0a6b-4bfe-b418-d366a4433fb9';

UPDATE exercise_variations SET coaching_cues = $$Hold onto something sturdy for balance and rise up onto the balls of your feet. Lean back from your knees, letting them travel forward, lowering your torso toward the floor while keeping a straight line from your knees to your shoulders, then drive back up. Keep your hips extended throughout — if your hips bend, you're turning it into a squat.$$ WHERE id = '1ecf3103-ae90-4875-86a2-2db4b525c304';

UPDATE exercise_variations SET coaching_cues = $$Lie on a bench holding the bar above your chest with a shoulder-width grip, arms extended. Bend only at the elbows to lower the bar toward your forehead (or just behind your head), then extend back up. Keep your upper arms still and vertical throughout — only your forearms should move.$$ WHERE id = '160c0a57-8e4f-46b9-8571-c9496d085208';

UPDATE exercise_variations SET coaching_cues = $$Lie on a bench positioned under a low pulley, holding the attachment above your chest with your arms extended. Bend only at the elbows to lower it toward your forehead, then extend back up. The cable keeps constant tension, so control the lowering phase rather than letting it drop.$$ WHERE id = '2a6ec160-36c4-465d-ba6a-7bcfc345a41f';

UPDATE exercise_variations SET coaching_cues = $$Lie on a bench holding a dumbbell in each hand above your chest, palms facing each other, arms extended. Bend only at the elbows to lower the weights toward your temples, then extend back up. Keep your upper arms still and vertical — only your forearms should be moving.$$ WHERE id = '949139cc-6de4-4cd6-807d-4336aba387dd';

UPDATE exercise_variations SET coaching_cues = $$Lie face-down on an incline bench with your arms hanging straight down, holding a dumbbell in each hand. Curl the weights up under control, squeezing hard at the top, then lower back down fully. The incline removes any ability to swing the weight, so keep the tempo slow and controlled.$$ WHERE id = '6c24bb95-9cea-478b-a200-5635766b7b05';

UPDATE exercise_variations SET coaching_cues = $$Set the bar across your upper back, feet wider than shoulder-width with toes turned out more than a standard squat. Squat down keeping your chest up and knees tracking over your toes, sitting back further than usual, then drive up through your heels. Sitting back and wide is what shifts the emphasis onto your glutes rather than your quads.$$ WHERE id = '839bab50-3136-4eec-b0c8-f046aff319df';

UPDATE exercise_variations SET coaching_cues = $$Stand with your feet wider than shoulder-width, toes turned out, hands clasped in front of you for balance. Squat down sitting back further than usual, keeping your chest up, then drive up through your heels. Focus on pushing your hips back rather than just bending your knees.$$ WHERE id = '4c0971fb-f60a-4bde-8070-734478463090';

UPDATE exercise_variations SET coaching_cues = $$Hold a kettlebell by the horns or handle against your chest, feet wider than shoulder-width with toes turned out. Squat down sitting back, keeping your chest tall, then drive up through your heels. Keep the kettlebell close to your body throughout to stay balanced.$$ WHERE id = '61612faf-3f1d-4e65-a1fe-4270ef935aa7';

UPDATE exercise_variations SET coaching_cues = $$Set the bar across your upper back in the Smith machine, feet set wider than shoulder-width and slightly forward of your hips, toes turned out. Squat down sitting back into the fixed path, then drive up through your heels. The fixed bar path lets you sit back further without worrying about balance.$$ WHERE id = '9c51c714-f40c-43e0-9950-c9146d29c32e';

UPDATE exercise_variations SET coaching_cues = $$Rest the bar across your upper back with a wide, stable grip, feet wider than shoulder-width and toes turned out. Squat down sitting back further than a standard squat, keeping your chest tall, then drive up through your heels. Push your hips back first before your knees bend, to keep the emphasis on your glutes.$$ WHERE id = 'd0d727ed-c236-42ff-a388-62eedba6f859';

UPDATE exercise_variations SET coaching_cues = $$Set the bar across your upper back, feet roughly shoulder-width apart. Squat down keeping your torso more upright than the glute-focused version, letting your knees travel forward over your toes, then drive back up. A more upright torso and narrower stance shifts the work onto your quads.$$ WHERE id = 'a88e36b1-0ddb-441c-96d0-53c55327157e';

UPDATE exercise_variations SET coaching_cues = $$Stand with your feet shoulder-width apart, arms out in front for balance. Squat down keeping your torso upright and knees tracking over your toes, going as deep as comfortable, then drive back up through your heels. Keep your heels flat on the floor throughout.$$ WHERE id = 'c03b6a37-a55d-45a5-99b7-3219c3d941a8';

UPDATE exercise_variations SET coaching_cues = $$Hold a kettlebell by the horns or handle against your chest, feet shoulder-width apart. Squat down keeping your torso upright, letting your knees travel forward over your toes, then drive back up. Keep your elbows tucked in close to your ribs so the weight doesn't pull you forward.$$ WHERE id = '7e4fadc2-5aa1-4251-ba22-cb5db1358470';

UPDATE exercise_variations SET coaching_cues = $$Set the bar across your upper back in the Smith machine, feet shoulder-width apart and slightly forward of your hips. Squat down along the fixed path keeping your torso upright, then drive back up through your heels. The fixed path lets you focus purely on depth and knee tracking.$$ WHERE id = '995ee4fe-08e6-4b7d-897c-61ba5fdcd87c';

UPDATE exercise_variations SET coaching_cues = $$Rest the bar across your upper back with a stable grip, feet shoulder-width apart. Squat down keeping your torso upright and knees tracking over your toes, then drive back up through your whole foot. Keep the bar path vertical over your mid-foot throughout.$$ WHERE id = '91a0d2f9-7256-4e4a-8de5-c777d29fe019';

UPDATE exercise_variations SET coaching_cues = $$Set your shoulders under the pads and the balls of your feet on the platform, heels hanging off the edge. Lower your heels down as far as comfortable, then press up onto your toes, pausing briefly at the top. Move slowly through the full range — bouncing at the bottom takes the tension off your calves.$$ WHERE id = '512ea9c6-824e-4a74-9c7e-cee9680f7a35';

UPDATE exercise_variations SET coaching_cues = $$Hold a dumbbell in each hand and place one foot fully on a box or bench in front of you. Drive through that foot to step up, avoiding pushing off your trailing leg, then step back down under control. Keep your weight through the heel of your working leg to keep the emphasis on your glutes.$$ WHERE id = '182f7239-e1b5-4df1-bfc2-4ee1ba300870';

UPDATE exercise_variations SET coaching_cues = $$Set the bar across your upper back in the Smith machine, with a box or bench positioned in front of you. Place one foot fully on the box and drive up through it without pushing off your trailing leg, then step back down under control. Keep your torso upright and your weight through your front heel.$$ WHERE id = '621856eb-5aec-464f-87df-a318c04d1d65';

UPDATE exercise_variations SET coaching_cues = $$Stand holding the bar at hip height, knees almost straight (a very slight bend only). Lower the bar down your legs by pushing your hips back, keeping your knees mostly locked, until you feel a strong stretch in your hamstrings, then drive your hips forward to stand. Keep the bar brushing your legs the whole way down and up.$$ WHERE id = 'd84b4e68-ecc3-4c0a-9a50-f9f80a70562c';

UPDATE exercise_variations SET coaching_cues = $$Stand facing a high pulley with a wide grip on the bar and your arms straight. Pull the bar down in an arc to your thighs, keeping your arms straight throughout, then let it rise back up under control. Keep your arms locked at a slight bend — this is a lat isolation move, not a tricep exercise.$$ WHERE id = '0b329e45-481a-443f-89f3-a539fe65f5ab';

UPDATE exercise_variations SET coaching_cues = $$Stand holding the bar at hip height with your legs almost fully straight. Push your hips back, keeping your knees locked in that slight bend, until you feel a deep stretch through your hamstrings, then drive your hips forward to stand tall. This is a bigger stretch than a standard RDL — go only as far as your hamstring flexibility allows without rounding your back.$$ WHERE id = '48735992-6a14-4138-b16e-964c1ae435e4';

UPDATE exercise_variations SET coaching_cues = $$Stand holding a dumbbell in each hand in front of your thighs, legs almost straight. Push your hips back, keeping your knees in that same slight bend, lowering the weights until you feel a deep hamstring stretch, then drive your hips forward to stand. Keep the dumbbells close to your legs throughout.$$ WHERE id = '5423b785-a9d0-4785-93aa-57ad4d579dc3';

UPDATE exercise_variations SET coaching_cues = $$Set up in the machine with the pad positioned for a hip hinge, keeping your knees almost straight throughout. Push your hips back against the resistance until you feel a deep stretch through your hamstrings, then drive your hips forward to extend. Keep your back flat and knees locked in that slight bend the whole set.$$ WHERE id = '28351968-831c-441c-b6d6-31af7d9c1bfa';

UPDATE exercise_variations SET coaching_cues = $$Stand with your feet wide, toes turned out, and grip the bar inside your legs. Push your hips down and back to set your shins vertical, then drive through the floor, keeping your chest up and the bar close to your body, to stand tall. Keep your knees tracking out over your toes throughout the pull.$$ WHERE id = 'fee73ab4-4f93-4c79-82e0-6a3fed324165';

UPDATE exercise_variations SET coaching_cues = $$Set the bar across your upper back, feet wide and toes turned out significantly more than a standard squat. Squat straight down keeping your torso upright, knees tracking out over your toes, then drive back up. Keep your chest tall throughout — the wide stance means there's less forward lean than a regular squat.$$ WHERE id = 'fc44892a-3a26-452a-a42b-f5c039925758';

UPDATE exercise_variations SET coaching_cues = $$Straddle the machine and grip the handles with your chest resting against the pad (or hinged forward if unsupported). Row the handles into your torso, driving your elbows back and squeezing your shoulder blades together, then lower under control. Keep your torso still throughout the set.$$ WHERE id = '37b396d0-04ae-48a2-85d3-33ee2586c048';

UPDATE exercise_variations SET coaching_cues = $$Hang from the bar with a full grip and your legs straight. Raise your legs up to touch the bar by curling your pelvis under and keeping your legs straight (or knees bent for an easier version), then lower back down under control. Control the lowering phase — swinging the legs down fast just sets you up to swing them back up with momentum instead of your abs.$$ WHERE id = '23db2ecd-0eb0-4d9e-b1c5-ffcde3133fb3';

UPDATE exercise_variations SET coaching_cues = $$Step inside the trap bar with your feet hip-width apart, gripping the handles at your sides. Push your hips down and back until your shins are vertical, keeping your chest up, then drive through the floor to stand tall. The neutral grip and centred weight make this an easier position to keep your back flat in than a standard barbell pull.$$ WHERE id = '7a13773b-143a-4408-8286-008bd47d39cd';

UPDATE exercise_variations SET coaching_cues = $$Support yourself on parallel bars (or a bench behind you) with your arms straight, torso upright rather than leaning forward. Lower yourself under control until your elbows reach about 90°, then press back up to full lockout. Keeping your torso upright (rather than leaning forward) is what shifts the emphasis onto your triceps.$$ WHERE id = 'e4f81f35-3bcb-4a8a-9139-f4e3f88841fd';

UPDATE exercise_variations SET coaching_cues = $$Grip the handles with your torso upright and your elbows tucked close to your body. Lower under control until your elbows reach about 90°, then press back up to full lockout. Keep your torso upright throughout to keep the focus on your triceps rather than your chest.$$ WHERE id = 'a037eded-9d10-4522-b1eb-96e6dcd88b37';

UPDATE exercise_variations SET coaching_cues = $$Stand facing a high pulley holding the attachment with both hands overhead, elbows pointing forward and close to your head. Extend your arms by straightening at the elbow, then bend to lower the weight back behind your head under control. Keep your elbows pinned in place — only your forearms should move.$$ WHERE id = 'da7d2a85-1766-4311-bec3-e9be42c45c14';

UPDATE exercise_variations SET coaching_cues = $$Stand or sit holding one dumbbell with both hands overhead, elbows pointing forward and close to your head. Lower the weight behind your head by bending only at the elbows, then extend back up. Keep your upper arms still throughout — flaring your elbows out turns this into a different movement.$$ WHERE id = 'e1d84880-9580-42f2-b1ec-569518db0137';

UPDATE exercise_variations SET coaching_cues = $$Lie on a bench or stand holding the EZ bar overhead with a grip on the angled part, elbows pointing forward. Lower the bar behind your head by bending only at the elbows, then extend back up. The angled grip is easier on the wrists, so use it to focus purely on the tricep stretch and squeeze.$$ WHERE id = 'f8e06821-db59-47d4-896d-657df59d2e2a';

UPDATE exercise_variations SET coaching_cues = $$Stand facing a high pulley holding the attachment with an overhand grip, elbows pinned to your sides. Push the attachment down until your arms are fully extended, squeezing your triceps hard, then let it rise back up under control without letting your elbows drift forward. Keep your elbows locked at your sides the entire set.$$ WHERE id = 'e8a43310-2a61-4e00-901c-b16607e13ff7';

UPDATE exercise_variations SET coaching_cues = $$Grip the handles at shoulder height with your palms facing each other (neutral grip), standing tall with your core braced. Press straight up until your arms are extended, then lower back down under control to shoulder height. The neutral grip is easier on the shoulders than a barbell press — keep your core tight so you don't lean back as you press.$$ WHERE id = 'e02bcb3a-7fc1-45f0-8d58-eb678d6e3cd5';

UPDATE exercise_variations SET coaching_cues = $$Grip the handles at shoulder height with a neutral grip, standing tall with your core braced. Press straight up until your arms are extended, then lower back down under control to shoulder height. Keep your core tight throughout so you don't lean back as you press.$$ WHERE id = 'a7a30630-8107-447b-b419-9134e99f3b00';

UPDATE exercise_variations SET coaching_cues = $$Hold a dumbbell in each hand and step forward into a lunge, lowering until your rear knee nearly touches the floor. Drive through your front heel to stand and step through into the next lunge on the other leg. Keep your torso upright throughout — leaning forward shifts the work off your quads.$$ WHERE id = '23a3621f-a29a-495d-9748-15f3f32cffbe';
