-- Bulk-populates exercise_alternatives across your whole library, based on
-- the exercise list you exported (grouped by primary_muscle, matched by
-- exact name — single coach account, so each name is unique). Pairs a genuinely
-- different movement/station for the same muscle, not an equipment variation
-- of the same exercise (those are already covered by each card's own
-- Variations tabs). Run once in Supabase SQL Editor — safe to re-run, ON
-- CONFLICT DO NOTHING skips anything already saved (e.g. from the manual
-- picker in the Exercise Library editor).
--
-- These are a sensible starting point — open any exercise in the Exercise
-- Library and use the "Alternative exercises" picker to add/remove from
-- this list any time.

INSERT INTO exercise_alternatives (exercise_id, alternative_exercise_id)
SELECT e1.id, e2.id
FROM (VALUES
  -- Back
  ('Bent Over Row', 'T-Bar Row'),
  ('Bent Over Row', 'Chest Supported Row'),
  ('Bent Over Row', 'Single Arm Row (Lats)'),
  ('T-Bar Row', 'Bent Over Row'),
  ('T-Bar Row', 'Chest Supported Row'),
  ('T-Bar Row', 'Low Row'),
  ('Chest Supported Row', 'Low Row'),
  ('Chest Supported Row', 'T-Bar Row'),
  ('Chest Supported Row', 'Seated Row (Lats)'),
  ('Low Row', 'Seated Row (Lats)'),
  ('Low Row', 'Chest Supported Row'),
  ('Low Row', 'T-Bar Row'),
  ('Seated Row (Lats)', 'Low Row'),
  ('Seated Row (Lats)', 'Single Arm Row (Lats)'),
  ('Seated Row (Lats)', 'Chest Supported Row'),
  ('Single Arm Row (Lats)', 'Seated Row (Lats)'),
  ('Single Arm Row (Lats)', 'Bent Over Row'),
  ('Deadlift', 'Trap Bar Deadlift'),
  ('Trap Bar Deadlift', 'Deadlift'),
  ('Face Pull', 'Rear Delt Face Pulls'),
  ('Face Pull', 'Rear Dealt Flys'),
  ('Lat Pulldown', 'Pull Up'),
  ('Lat Pulldown', 'Straight Arm Pulldown'),
  ('Lat Pulldown', 'Lat Pullover'),
  ('Pull Up', 'Lat Pulldown'),
  ('Lat Pullover', 'Lat Pulldown'),
  ('Lat Pullover', 'Straight Arm Pulldown'),
  ('Straight Arm Pulldown', 'Lat Pullover'),
  ('Straight Arm Pulldown', 'Lat Pulldown'),

  -- Biceps
  ('Bicep Curl', 'Cable Curl'),
  ('Bicep Curl', 'Hammer Curl'),
  ('Bicep Curl', 'Preacher Curl'),
  ('Cable Curl', 'Bicep Curl'),
  ('Cable Curl', 'Preacher Curl'),
  ('Hammer Curl', 'Bicep Curl'),
  ('Hammer Curl', 'Cable Curl'),
  ('Preacher Curl', 'Spider Curl'),
  ('Preacher Curl', 'Concentration Curl'),
  ('Preacher Curl', 'Cable Curl'),
  ('Spider Curl', 'Preacher Curl'),
  ('Spider Curl', 'Concentration Curl'),
  ('Concentration Curl', 'Spider Curl'),
  ('Concentration Curl', 'Preacher Curl'),

  -- Calves
  ('Seated Calf Raise', 'Standing Calf Raise'),
  ('Standing Calf Raise', 'Seated Calf Raise'),

  -- Chest
  ('Bench Press', 'Incline Chest Press'),
  ('Bench Press', 'Push Up'),
  ('Bench Press', 'Dips'),
  ('Incline Chest Press', 'Bench Press'),
  ('Incline Chest Press', 'Push Up'),
  ('Push Up', 'Bench Press'),
  ('Push Up', 'Dips'),
  ('Push Up', 'Incline Chest Press'),
  ('Dips', 'Push Up'),
  ('Dips', 'Bench Press'),
  ('Chest Fly', 'High to Low Cable Fly'),
  ('Chest Fly', 'Low to High Cable Fly'),
  ('High to Low Cable Fly', 'Low to High Cable Fly'),
  ('High to Low Cable Fly', 'Chest Fly'),
  ('Low to High Cable Fly', 'High to Low Cable Fly'),
  ('Low to High Cable Fly', 'Chest Fly'),

  -- Core
  ('Ab Wheel Rollout', 'Plank'),
  ('Ab Wheel Rollout', 'Dead Bug'),
  ('Plank', 'Side Plank'),
  ('Plank', 'Dead Bug'),
  ('Side Plank', 'Plank'),
  ('Dead Bug', 'Plank'),
  ('Dead Bug', 'Ab Wheel Rollout'),
  ('Cable Crunch', 'Crunches'),
  ('Cable Crunch', 'Ab Wheel Rollout'),
  ('Crunches', 'Cable Crunch'),
  ('Crunches', 'Russian Twist'),
  ('Russian Twist', 'Crunches'),
  ('Russian Twist', 'Cable Crunch'),
  ('Hanging Leg Raise', 'Toes to Bar'),
  ('Hanging Leg Raise', 'Cable Crunch'),
  ('Toes to Bar', 'Hanging Leg Raise'),
  ('Toes to Bar', 'Cable Crunch'),

  -- Glutes
  ('Bulgarian Split Squat (Glutes)', 'Reverse Lunges (Glutes)'),
  ('Bulgarian Split Squat (Glutes)', 'Step-Ups'),
  ('Bulgarian Split Squat (Glutes)', 'Single Leg Romanian Deadlift'),
  ('Reverse Lunges (Glutes)', 'Bulgarian Split Squat (Glutes)'),
  ('Reverse Lunges (Glutes)', 'Step-Ups'),
  ('Step-Ups', 'Reverse Lunges (Glutes)'),
  ('Step-Ups', 'Bulgarian Split Squat (Glutes)'),
  ('Cable Kickback', 'Hip Abduction'),
  ('Hip Abduction', 'Cable Kickback'),
  ('Cable Pull Through', 'Good Mornings'),
  ('Cable Pull Through', 'Hip Thrust'),
  ('Cable Pull Through', 'RDLs (Glutes)'),
  ('Good Mornings', 'Cable Pull Through'),
  ('Good Mornings', 'RDLs (Glutes)'),
  ('Good Mornings', 'Hyperextensions'),
  ('Hyperextensions', 'Good Mornings'),
  ('Hyperextensions', 'Hip Thrust'),
  ('Hip Thrust', 'Hip Thrust - Hold'),
  ('Hip Thrust', 'Cable Pull Through'),
  ('Hip Thrust', 'Hyperextensions'),
  ('Hip Thrust - Hold', 'Hip Thrust'),
  ('Hip Thrust - Hold', 'Cable Pull Through'),
  ('Deep Goblet Squats', 'Sumo Squat'),
  ('Deep Goblet Squats', 'Squat (Glutes)'),
  ('Deep Goblet Squats', 'Leg Press (Glute Focussed)'),
  ('Squat (Glutes)', 'Deep Goblet Squats'),
  ('Squat (Glutes)', 'Sumo Squat'),
  ('Squat (Glutes)', 'Leg Press (Glute Focussed)'),
  ('Sumo Squat', 'Sumo Deadlift'),
  ('Sumo Squat', 'Deep Goblet Squats'),
  ('Sumo Squat', 'Squat (Glutes)'),
  ('Sumo Deadlift', 'Sumo Squat'),
  ('Sumo Deadlift', 'RDLs (Glutes)'),
  ('Leg Press (Glute Focussed)', 'Deep Goblet Squats'),
  ('Leg Press (Glute Focussed)', 'Squat (Glutes)'),
  ('RDLs (Glutes)', 'Single Leg Romanian Deadlift'),
  ('RDLs (Glutes)', 'Good Mornings'),
  ('RDLs (Glutes)', 'Sumo Deadlift'),
  ('Single Leg Romanian Deadlift', 'RDLs (Glutes)'),
  ('Single Leg Romanian Deadlift', 'Bulgarian Split Squat (Glutes)'),

  -- Hamstrings
  ('Kettlebell Swing', 'Stiff Leg Deadlift'),
  ('Kettlebell Swing', 'Straight Leg RDL'),
  ('Stiff Leg Deadlift', 'Straight Leg RDL'),
  ('Stiff Leg Deadlift', 'Kettlebell Swing'),
  ('Straight Leg RDL', 'Stiff Leg Deadlift'),
  ('Straight Leg RDL', 'Kettlebell Swing'),
  ('Lying Hamstring Curl', 'Seated Hamstring Curl'),
  ('Seated Hamstring Curl', 'Lying Hamstring Curl'),

  -- Quads
  ('Back Squat', 'Front Squat'),
  ('Back Squat', 'Hack Squat'),
  ('Back Squat', 'Leg Press (Quad Focus)'),
  ('Back Squat', 'Box Squat'),
  ('Box Squat', 'Back Squat'),
  ('Box Squat', 'Hack Squat'),
  ('Front Squat', 'Back Squat'),
  ('Front Squat', 'Goblet Squat'),
  ('Front Squat', 'Hack Squat'),
  ('Goblet Squat', 'Front Squat'),
  ('Goblet Squat', 'Leg Press (Quad Focus)'),
  ('Hack Squat', 'Back Squat'),
  ('Hack Squat', 'Leg Press (Quad Focus)'),
  ('Hack Squat', 'Pendulum Squat'),
  ('Squat (Quads)', 'Back Squat'),
  ('Squat (Quads)', 'Front Squat'),
  ('Squat (Quads)', 'Hack Squat'),
  ('Squat (Quads)', 'Leg Press (Quad Focus)'),
  ('Leg Press (Quad Focus)', 'Hack Squat'),
  ('Leg Press (Quad Focus)', 'Pendulum Squat'),
  ('Leg Press (Quad Focus)', 'Single Leg Press'),
  ('Pendulum Squat', 'Hack Squat'),
  ('Pendulum Squat', 'Leg Press (Quad Focus)'),
  ('Single Leg Press', 'Bulgarian Split Squat (Quads)'),
  ('Single Leg Press', 'Leg Press (Quad Focus)'),
  ('Bulgarian Split Squat (Quads)', 'Walking Lunge'),
  ('Bulgarian Split Squat (Quads)', 'Single Leg Press'),
  ('Walking Lunge', 'Bulgarian Split Squat (Quads)'),
  ('Walking Lunge', 'Single Leg Press'),
  ('Leg Extensions', 'Sissy Squat'),
  ('Sissy Squat', 'Leg Extensions'),

  -- Shoulders
  ('Shoulder Press', 'Military Press'),
  ('Shoulder Press', 'Viking Press'),
  ('Military Press', 'Shoulder Press'),
  ('Military Press', 'Viking Press'),
  ('Viking Press', 'Shoulder Press'),
  ('Viking Press', 'Military Press'),
  ('Lateral Raise', 'Seated Lateral Raise'),
  ('Lateral Raise', 'Plate Raise'),
  ('Seated Lateral Raise', 'Lateral Raise'),
  ('Seated Lateral Raise', 'Plate Raise'),
  ('Plate Raise', 'Lateral Raise'),
  ('Plate Raise', 'Seated Lateral Raise'),
  ('Incline Rear Delt Raise', 'Rear Dealt Flys'),
  ('Incline Rear Delt Raise', 'Rear Delt Face Pulls'),
  ('Rear Dealt Flys', 'Incline Rear Delt Raise'),
  ('Rear Dealt Flys', 'Rear Delt Face Pulls'),
  ('Rear Delt Face Pulls', 'Rear Dealt Flys'),
  ('Rear Delt Face Pulls', 'Incline Rear Delt Raise'),
  ('Rear Delt Face Pulls', 'Face Pull'),

  -- Triceps
  ('Close Grip Bench Press', 'Skull Crusher'),
  ('Close Grip Bench Press', 'Tricep Dips'),
  ('Skull Crusher', 'Close Grip Bench Press'),
  ('Skull Crusher', 'Tricep Extensions'),
  ('Tricep Dips', 'Close Grip Bench Press'),
  ('Tricep Dips', 'Tricep Pushdown'),
  ('Overhead Tricep Extension', 'Tricep Extensions'),
  ('Overhead Tricep Extension', 'Tricep Pushdown'),
  ('Tricep Extensions', 'Overhead Tricep Extension'),
  ('Tricep Extensions', 'Tricep Pushdown'),
  ('Tricep Extensions', 'Skull Crusher'),
  ('Tricep Pushdown', 'Tricep Extensions'),
  ('Tricep Pushdown', 'Overhead Tricep Extension'),
  ('Tricep Pushdown', 'Tricep Dips')
) AS pairs(exercise_name, alternative_name)
JOIN exercises e1 ON e1.name = pairs.exercise_name
JOIN exercises e2 ON e2.name = pairs.alternative_name
ON CONFLICT (exercise_id, alternative_exercise_id) DO NOTHING;
