-- Add category column and update all ingredients
ALTER TABLE ingredients ADD COLUMN IF NOT EXISTS category text;

UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Baby Potatoes (Raw)');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Baby Potatoes (Boiled)');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Bagel');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Bagel Thin');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Baking Potato');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Banana');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Brioche Bun');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Caramel Rice Cake');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Chocolate Rice Cake');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Cibatta Roll');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Cinnamon and Raisin Bagel');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Coco Pops');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Corn Flakes');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Corn Flour');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Cream of Rice');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Crumpets');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Crumpet Thin');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Pitted Dates');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Frosties');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Gluten Free Bagel');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Gluten Free Bun');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Gluten Free Oats');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Gluten Free Penne Pasta (Dry)');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Gluten Free Pita');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Gluten Free Spaghetti (Dry)');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Gluten Free Wrap');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Gluten Free Wrap (Small)');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Honey');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Hot Cross Bun - Flavoured');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Hovis Medium Wholemeal');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Jam');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Jason''s No.9 Wholemeal Sourdough');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Lasagne Sheet');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Medium Egg Noodles');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Medjool Dates');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Semi-Skimmed Milk');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Oat Milk');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Oats');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Orzo (dry)');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Panini');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Penne Pasta (Cooked)');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Penne Pasta (Uncooked)');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Plain Flour');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Pita Bread');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Rice (Cooked)');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Rice (Uncooked)');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Rice Crispies');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Rice Crispies Squares Bar');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Salt and Vinegar Rice Cake');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Salted Rice Cakes');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Self-Raising Flour');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Small Wrap');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Wholemeal Sourdough');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Spaghetti (Dry)');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Spaghetti Hoops');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Sweet Potato (Raw)');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Sweet Potato Wrap');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Taco Shells');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Tortilla Wrap');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Warbutons NAS Wholemeal');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Weetabix');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Wholemeal Bap');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('Wholemeal Rice (Cooked)');
UPDATE ingredients SET category = 'carbohydrates' WHERE LOWER(name) = LOWER('White Bap');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('0% Greek Style Yogurt');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('0% Greek Yogurt');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('5% Fat Chicken Mince (raw)');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('5% Fat Mince (Uncooked)');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Bacon Medallions');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Baked Beans');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Chicken (Cooked)');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Chicken (Raw)');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Chicken Chipolata Sausages');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Chicken Sausages');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Chickpeas');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Cooked Chicken');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Cottage Cheese');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Chorizo');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Eggs');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Egg White');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Full Fat Greek Style Yogurt');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Full fat Greek Yogurt');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Gammon');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Isolate Protein Powder');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Kidney Beans');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Kidney Beans In Chilli Sauce');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Parmesan');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Protein Mousse');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Protein Yogurt (Pouch)');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Roast Chicken Wafer Thin Slices');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Ready Cooked Chicken');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Salmon Fillet');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Sirloin Steak (Raw)');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Sourdough');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('0% Strawberry Skyr');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Tin of Beans');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Turkey Slice');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Tuna');
UPDATE ingredients SET category = 'protein' WHERE LOWER(name) = LOWER('Wafer Thin Honey Roast Ham');
UPDATE ingredients SET category = 'fats' WHERE LOWER(name) = LOWER('70% Dark Chocolate');
UPDATE ingredients SET category = 'fats' WHERE LOWER(name) = LOWER('85% Dark Chocolate (12.5g)');
UPDATE ingredients SET category = 'fats' WHERE LOWER(name) = LOWER('Almonds');
UPDATE ingredients SET category = 'fats' WHERE LOWER(name) = LOWER('Avacado');
UPDATE ingredients SET category = 'fats' WHERE LOWER(name) = LOWER('Butter');
UPDATE ingredients SET category = 'fats' WHERE LOWER(name) = LOWER('Chia Seeds');
UPDATE ingredients SET category = 'fats' WHERE LOWER(name) = LOWER('Flaxseeds');
UPDATE ingredients SET category = 'fats' WHERE LOWER(name) = LOWER('Garlic and Herb Butter');
UPDATE ingredients SET category = 'fats' WHERE LOWER(name) = LOWER('Granola');
UPDATE ingredients SET category = 'fats' WHERE LOWER(name) = LOWER('Olive Oil');
UPDATE ingredients SET category = 'fats' WHERE LOWER(name) = LOWER('Peanut Butter');
UPDATE ingredients SET category = 'fats' WHERE LOWER(name) = LOWER('Walnuts');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Apple');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Aspagargus');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Bean Sprouts');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Broccoli');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Carrot');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Celery');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Cherry Tomatoes');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Chopped Tomatoes');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Coriander');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Crinkle Cut Gherkins');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Cucumber');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Garden Peas (cooked)');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Garlic');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Grapes');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Green Beans');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Kiwi');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Leeks');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Lettuce');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Onion');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Mushrooms');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Parsnip');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Pepper');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Raspberries');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Salad');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Spinach');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Strawberries');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Sun-Dried Tomatos');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Spring Onion');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Steam Bag');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Sweetcorn');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Swede');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Tenderstem Broccoli');
UPDATE ingredients SET category = 'vegetables' WHERE LOWER(name) = LOWER('Tomato');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Baking Powder');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('BBQ Sauce');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Beef Stock Cube');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Berries');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Biscoff Spread');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Breakfast Topper');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Burger Sauce');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Cheese (50% Lighter)');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Chicken Stock Cube');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Chocolate Chips');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Fajita Seasoning');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Feta Cheese');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Halloumi');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Light cream Cheese');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Lightest Philadelphia');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Light Soy Sauce');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Stir Fry Sauce');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Light Mayo');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Lighter than Light Mayo');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Mayflower Curry Sauce');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Mustard (Wholegrain)');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Nandos Sweet Chilli Jam');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Nandos Peri Peri Sauce');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Nutella');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Oyster Sauce');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Reduced Lasagne Sauce');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Reduced Crème Fresh');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Reduced Ketchup');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Reduced Pesto');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Reduced Red Pesto');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Reduced Sweet Chilli Sauce');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Salad Cream (50% Reduced)');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Salsa');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Red Pesto');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Red Wine Stock Pot');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Reduced Gravy Granules');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Reggae Reggae Sauce');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Spreadable Butter (Lighter)');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Taco Seasoning');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Tomato Mascarpone Sauce');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Panko Breadcrumbs');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Passata');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('Tomato Puree');
UPDATE ingredients SET category = 'toppings' WHERE LOWER(name) = LOWER('50% Plastic Cheese Slice');
UPDATE ingredients SET category = 'snacks' WHERE LOWER(name) = LOWER('Digestive Biscuit');
UPDATE ingredients SET category = 'snacks' WHERE LOWER(name) = LOWER('Kinder Bar');
UPDATE ingredients SET category = 'snacks' WHERE LOWER(name) = LOWER('Dairy Milk Little Bar');
UPDATE ingredients SET category = 'snacks' WHERE LOWER(name) = LOWER('Twirl Bar (43g)');