-- Reverts everything the two import scripts run earlier today may have added:
-- new meals (add-new-meals-from-spreadsheet.sql) and new ingredients
-- (add-ingredient-library-foods.sql). Scoped tightly so it cannot touch anything
-- you had before today: a row is only deleted if BOTH its name/category exactly
-- matches one of the candidates those scripts tried to insert AND its created_at
-- is today -- anything you already had (which the scripts' NOT EXISTS / ON CONFLICT
-- guards would have skipped) keeps its original older created_at and is left alone.
-- Deleting a meal cascades to delete its own meal_ingredients rows automatically.

-- 1) Undo today's new meals
with candidates(name, category) as (
  values
  ('Overnight Oats', 'breakfast'),
  ('Breakfast Bagel', 'breakfast'),
  ('PB&J Bagel', 'breakfast'),
  ('Porridge', 'breakfast'),
  ('Eggs', 'breakfast'),
  ('Yogurt', 'breakfast'),
  ('Overnight Weetabix', 'breakfast'),
  ('Avacado on Toast', 'breakfast'),
  ('Breafkast Wrap', 'breakfast'),
  ('Protein Pancakes', 'breakfast'),
  ('Chia Pudding', 'breakfast'),
  ('Chicken Sausage Bagel', 'breakfast'),
  ('Honey Bagel', 'breakfast'),
  ('Avacado and Egg', 'breakfast'),
  ('Oats and Water', 'breakfast'),
  ('Sticky Toffee Baked Oats', 'breakfast'),
  ('Carrot Cake Baked Oats', 'breakfast'),
  ('Flavoured Hot Cross Bun', 'breakfast'),
  ('Apple Crumble Baked Oats', 'breakfast'),
  ('Jam Crumpets', 'breakfast'),
  ('Sausages, Beans and Toast', 'breakfast'),
  ('Biscoff Overnight Oats', 'breakfast'),
  ('Strawberry Cheesecake Overnight Oats', 'breakfast'),
  ('Jam Bagel', 'breakfast'),
  ('Sweet Chilli Chicken Wrap', 'lunch'),
  ('Chicken Sausage Bagel', 'lunch'),
  ('Avacado and Egg on Sourdough', 'lunch'),
  ('Chicken and Rice', 'lunch'),
  ('Tuna Pasta', 'lunch'),
  ('Chicken and Sweet Potato', 'lunch'),
  ('Beans on Toast', 'lunch'),
  ('Tuna Bun', 'lunch'),
  ('Tuna Pita', 'lunch'),
  ('Avacado Bagel', 'lunch'),
  ('Tuna Bagel', 'lunch'),
  ('Chicken and Egg Fried Rice', 'lunch'),
  ('BBQ Chicken Wrap', 'lunch'),
  ('Jerk Chicken Cheese Burger', 'lunch'),
  ('Club Sandwich', 'lunch'),
  ('Cheesy Chicken and Chorizo Wrap', 'lunch'),
  ('Cheese Burger Wrap', 'lunch'),
  ('Nandos Chicken Cibatta', 'lunch'),
  ('Scrambled Egg Bagel', 'lunch'),
  ('Roasted Tomato Pepper and Feta Soup', 'lunch'),
  ('Chicken and Veg Soup', 'lunch'),
  ('Chicken Salad', 'lunch'),
  ('Crispy Chilli Chicken Wrap', 'lunch'),
  ('BBQ Chicken Pita', 'lunch'),
  ('Pesto Chicken Cibatta', 'lunch'),
  ('Pesto Chicken Pannini', 'lunch'),
  ('Egg Salad Bun', 'lunch'),
  ('Ham and Cheese Toastie', 'lunch'),
  ('Chicken Pita', 'lunch'),
  ('Chicken, Rice and Veg', 'lunch'),
  ('Chicken Caesar Salad', 'lunch'),
  ('Roast Ham Sandwich', 'lunch'),
  ('Naked Borrito', 'lunch'),
  ('Rice Cakes', 'pre_workout'),
  ('Cereal', 'pre_workout'),
  ('Oats', 'pre_workout'),
  ('Bagel Thin', 'pre_workout'),
  ('Sweet Potato', 'pre_workout'),
  ('Crumpets', 'pre_workout'),
  ('Squares Bar and Banana', 'pre_workout'),
  ('Protein Yogurt (Pouch)', 'pre_workout'),
  ('Jam Crumpet Thins', 'pre_workout'),
  ('Jam Bagel', 'pre_workout'),
  ('Steak and Poatoes', 'dinner'),
  ('Chicken and Potatos', 'dinner'),
  ('Fajitas', 'dinner'),
  ('Smash Burger', 'dinner'),
  ('Salmon and Potatoes', 'dinner'),
  ('Stir Fry', 'dinner'),
  ('Chicken and Rice', 'dinner'),
  ('Chicken Burger', 'dinner'),
  ('Burger Bowl', 'dinner'),
  ('Tortilla Pizza', 'dinner'),
  ('Chicken and Sweet Potato', 'dinner'),
  ('Sticky Honey Chicken and Rice', 'dinner'),
  ('Cheesy Beef Pasta', 'dinner'),
  ('Creamy Chicken Pasta', 'dinner'),
  ('Chicken, Hallouimi and Chorizo Pasta', 'dinner'),
  ('Sweet Chilli Chicken Egg Fried Rice', 'dinner'),
  ('Creamy Garlic Cheesy Chicken & Potatos', 'dinner'),
  ('Cheesy BBQ Chicken Loaded Fries', 'dinner'),
  ('Creamy Cajun Chicken Pasta', 'dinner'),
  ('Chicken and Chorizo Rice', 'dinner'),
  ('Spaghetti Bolognase', 'dinner'),
  ('BBQ Chicken Pizza', 'dinner'),
  ('Big Mac Loaded Fries', 'dinner'),
  ('Chilli and Wedges', 'dinner'),
  ('Nandos Orzo', 'dinner'),
  ('Chicken Sausage and Mascarpone', 'dinner'),
  ('Chicken and Bacon Potato Pie', 'dinner'),
  ('Jacket Potato, Tuna, Cheese and Onion', 'dinner'),
  ('Chicken Fajitas', 'dinner'),
  ('Creamy Nandos Chicken Pasta', 'dinner'),
  ('Beef Tacos', 'dinner'),
  ('Mayflower Curry', 'dinner'),
  ('Chicken Pita and Sweet Potato Fries', 'dinner'),
  ('Chicken Chow Mein', 'dinner'),
  ('Potato Fajitas', 'dinner'),
  ('Jacket Potato, Beans and Cheese', 'dinner'),
  ('Chicken Sausage and Sweet Potato Mash', 'dinner'),
  ('Reduced Lasange', 'dinner'),
  ('Cheesey Chicken and Broccoli Pasta', 'dinner'),
  ('Greek Yogurt', 'evening_snack'),
  ('Bagel Thin', 'evening_snack'),
  ('Rice Cakes', 'evening_snack'),
  ('Cinnamon and Raisin Bagel', 'evening_snack'),
  ('Peanut Butter Bagel Thin', 'evening_snack'),
  ('Kinder Protein Cheesecake', 'snack'),
  ('Banana and Raspberry Biscoff Baked Oats', 'snack')
)
delete from meals m
using candidates c
where m.coach_id = (select id from profiles where email = 'annabelatherton@gmail.com')
  and m.category = c.category
  and lower(trim(m.name)) = lower(trim(c.name))
  and m.created_at::date = current_date;

-- 2) Undo today's new ingredients
with candidates(name) as (
  values
  ('Baby Potatoes (Raw)'),
  ('Baby Potatoes (Boiled)'),
  ('Bagel'),
  ('Bagel Thin'),
  ('Baking Potato'),
  ('Banana'),
  ('Brioche Bun'),
  ('Caramel Rice Cake'),
  ('Chocolate Rice Cake'),
  ('Cibatta Roll'),
  ('Cinnamon and Raisin Bagel'),
  ('Coco Pops'),
  ('Corn Flakes'),
  ('Corn Flour'),
  ('Cream of Rice'),
  ('Crumpets'),
  ('Crumpet Thin'),
  ('Pitted Dates'),
  ('Frosties'),
  ('Gluten Free Bagel'),
  ('Gluten Free Bun'),
  ('Gluten Free Oats'),
  ('Gluten Free Penne Pasta (Dry)'),
  ('Gluten Free Pita'),
  ('Gluten Free Spaghetti (Dry)'),
  ('Gluten Free Wrap'),
  ('Gluten Free Wrap (Small)'),
  ('Honey'),
  ('Hot Cross Bun - Flavoured'),
  ('Hovis Medium Wholemeal'),
  ('Jam'),
  ('Jason''s No.9 Wholemeal Sourdough'),
  ('Kallo Beetroot Veggie Cake'),
  ('Lasagne Sheet'),
  ('Medium Egg Noodles'),
  ('Medjool Dates'),
  ('Semi-Skimmed Milk'),
  ('Oat Milk'),
  ('Oats'),
  ('Orzo (dry)'),
  ('Panini'),
  ('Penne Pasta (Cooked)'),
  ('Penne Pasta (Uncooked)'),
  ('Plain Flour'),
  ('Pita Bread'),
  ('Rice (Cooked)'),
  ('Rice (Uncooked)'),
  ('Rice Crispies'),
  ('Rice Crispies Squares Bar'),
  ('Salt and Vinegar Rice Cake'),
  ('Salted Rice Cakes'),
  ('Self-Raising Flour'),
  ('Small Wrap'),
  ('Wholemeal Sourdough'),
  ('Spaghetti (Dry)'),
  ('Spaghetti Hoops'),
  ('Sweet Potato (Raw)'),
  ('Sweet Potato Wrap'),
  ('Taco Shells'),
  ('Tortilla Wrap'),
  ('Warbutons NAS Wholemeal'),
  ('Weetabix'),
  ('Wholemeal Bap'),
  ('Wholemeal Rice (Cooked)'),
  ('White Bap'),
  ('0% Greek Style Yogurt'),
  ('0% Greek Yogurt'),
  ('5% Fat Chicken Mince (raw)'),
  ('5% Fat Mince (Uncooked)'),
  ('Bacon Medallions'),
  ('Baked Beans'),
  ('Chicken (Cooked)'),
  ('Chicken (Raw)'),
  ('Chicken Chipolata Sausages'),
  ('Chicken Sausages'),
  ('Chickpeas'),
  ('Cooked Chicken'),
  ('Cottage Cheese'),
  ('Chorizo'),
  ('Eggs'),
  ('Egg White'),
  ('Full Fat Greek Style Yogurt'),
  ('Full fat Greek Yogurt'),
  ('Gammon'),
  ('Isolate Protein Powder'),
  ('Kidney Beans'),
  ('Kidney Beans In Chilli Sauce'),
  ('Parmesan'),
  ('Protein Mousse'),
  ('Protein Yogurt (Pouch)'),
  ('Roast Chicken Wafer Thin Slices'),
  ('Ready Cooked Chicken'),
  ('Salmon Fillet'),
  ('Sirloin Steak (Raw)'),
  ('Sourdough'),
  ('0% Strawberry Skyr'),
  ('Tin of Beans'),
  ('Turkey Slice'),
  ('Tuna'),
  ('Wafer Thin Honey Roast Ham'),
  ('70% Dark Chocolate'),
  ('85% Dark Chocolate (12.5g)'),
  ('Almonds'),
  ('Avacado'),
  ('Butter'),
  ('Chia Seeds'),
  ('Flaxseeds'),
  ('Garlic and Herb Butter'),
  ('Granola'),
  ('Olive Oil'),
  ('Peanut Butter'),
  ('Walnuts'),
  ('Apple'),
  ('Asparagus'),
  ('Bean Sprouts'),
  ('Broccoli'),
  ('Carrot'),
  ('Celery'),
  ('Cherry Tomatoes'),
  ('Chopped Tomatoes'),
  ('Coriander'),
  ('Crinkle Cut Gherkins'),
  ('Cucumber'),
  ('Country Vegetable Mix (Frozen)'),
  ('Garden Peas (cooked)'),
  ('Garlic'),
  ('Grapes'),
  ('Green Beans'),
  ('Kiwi'),
  ('Leeks'),
  ('Lettuce'),
  ('Onion'),
  ('Mushrooms'),
  ('Parsnip'),
  ('Pepper'),
  ('Raspberries'),
  ('Salad'),
  ('Spinach'),
  ('Strawberries'),
  ('Sun-Dried Tomatos'),
  ('Spring Onion'),
  ('Steam Bag'),
  ('Sweetcorn'),
  ('Swede'),
  ('Tenderstem Broccoli'),
  ('Tomato'),
  ('Baking Powder'),
  ('BBQ Sauce'),
  ('Beef Stock Cube'),
  ('Berries'),
  ('Biscoff Spread'),
  ('Breakfast Topper'),
  ('Burger Sauce'),
  ('Cheese (50% Lighter)'),
  ('Chicken Stock Cube'),
  ('Chocolate Chips'),
  ('Fajita Seasoning'),
  ('Feta Cheese'),
  ('Halloumi'),
  ('Light cream Cheese'),
  ('Lightest Philadelphia'),
  ('Light Soy Sauce'),
  ('Stir Fry Sauce'),
  ('Light Mayo'),
  ('Lighter than Light Mayo'),
  ('Mayflower Curry Sauce'),
  ('Mustard (Wholegrain)'),
  ('Nandos Sweet Chilli Jam'),
  ('Nandos Peri Peri Sauce'),
  ('Nutella'),
  ('Oatly Barista'),
  ('Oyster Sauce'),
  ('Reduced Lasagne Sauce'),
  ('Reduced Crème Fresh'),
  ('Reduced Ketchup'),
  ('Reduced Pesto'),
  ('Reduced Red Pesto'),
  ('Reduced Sweet Chilli Sauce'),
  ('Salad Cream (50% Reduced)'),
  ('Salsa'),
  ('Red Pesto'),
  ('Red Wine Stock Pot'),
  ('Reduced Caesar Dressing'),
  ('Reduced Gravy Granules'),
  ('Reggae Reggae Sauce'),
  ('Spreadable Butter (Lighter)'),
  ('Taco Seasoning'),
  ('Tomato Mascarpone Sauce'),
  ('Panko Breadcrumbs'),
  ('Passata'),
  ('Tomato Puree'),
  ('50% Plastic Cheese Slice'),
  ('Digestive Biscuit'),
  ('Kinder Bar'),
  ('Dairy Milk Little Bar'),
  ('Twirl Bar (43g)'),
  ('Quorn Chicken Pieces'),
  ('Quorn Mince'),
  ('Quorn Sausages'),
  ('Quorn Ham Slices')
)
delete from ingredients i
using candidates c
where i.coach_id = (select id from profiles where email = 'annabelatherton@gmail.com')
  and lower(trim(i.name)) = lower(trim(c.name))
  and i.created_at::date = current_date;
